#include "os.h"
#include <os_io_seproxyhal.h>
#include "glyphs.h"
#include "incognito_ux.h"
#include "incognito_api.h"
#include <stdint.h>
#include <stdbool.h>
commandContext global;
ux_state_t ux;

// Here we define the main menu, using the Ledger-provided menu API. This menu
// turns out to be fairly unimportant for Nano S apps, since commands are sent
// by the computer instead of being initiated by the user. It typically just
// contains an idle screen and a version screen.

// This is a forward declaration, since menu_about needs to reference
// menu_main.
static const ux_menu_entry_t menu_main[];

static const ux_menu_entry_t menu_about[] = {
    // I won't bother describing how menus work in detail, since it's fairly
    // self-evident and not very useful; but to save you some trouble, this
    // first element is defined with explicit fields, so you can see what they
    // all are.
    {
        .menu = NULL,		 // another menu entry, displayed when this item is "entered"
        .callback = NULL,	 // a function that takes a userid, called when this item is entered
        .userid = 0,		 // a custom identifier, helpful for implementing custom menu behavior
        .icon = NULL,		 // the glyph displayed next to the item text
        .line1 = "Version",	 // the first line of text
        .line2 = APPVERSION, // the second line of text; if NULL, line1 will be vertically centered
        .text_x = 0,		 // the x offset of the lines of text; only used if non-zero
        .icon_x = 0,		 // the x offset of the icon; only used if non-zero
    },
    // This element references a custom glyph, C_icon_back. This glyph is
    // defined in glyphs.c, which was generated by the Makefile from the
    // corresponding .gif file in the glyphs/ folder. If you drop your own
    // .gif files into this folder and run make, they will likewise become
    // available for use in your app. The SDK also defines a few built-in
    // icons, such as BAGL_GLYPH_ICON_CHECK, which you'll see in the screen
    // definitions later on.
    {menu_main, NULL, 0, &C_icon_back, "Back", NULL, 61, 40},
    UX_MENU_END,
    };

static const ux_menu_entry_t menu_main[] = {
    {NULL, NULL, 0, NULL, "Waiting for", "commands...", 0, 0},
    {menu_about, NULL, 0, NULL, "About", NULL, 0, 0},
    {NULL, os_sched_exit, 0, &C_icon_dashboard, "Quit app", NULL, 50, 29},
    UX_MENU_END,
    };

// ui_idle displays the main menu. Note that your app isn't required to use a
// menu as its idle screen; you can define your own completely custom screen.
void ui_idle(void)
    {
    // The first argument is the starting index within menu_main, and the last
    // argument is a preprocessor; I've never seen an app that uses either
    // argument.
    UX_MENU_DISPLAY(0, menu_main, NULL);
    }

// io_exchange_with_code is a helper function for sending response APDUs from
// button handlers. Note that the IO_RETURN_AFTER_TX flag is set. 'tx' is the
// conventional name for the size of the response APDU, i.e. the write-offset
// within G_io_apdu_buffer.
void io_exchange_with_code(uint16_t code, uint16_t tx)
    {
    G_io_apdu_buffer[tx++] = code >> 8;
    G_io_apdu_buffer[tx++] = code & 0xFF;
    io_exchange(CHANNEL_APDU | IO_RETURN_AFTER_TX, tx);
    }

static void incognito_main(void)
    {
    volatile unsigned int rx = 0;
    volatile unsigned int tx = 0;
    volatile unsigned int flags = 0;

    for (;;)
        {
        volatile unsigned short sw = 0;
        BEGIN_TRY
            {
                TRY
                {
                    rx = tx;
                    tx = 0; // ensure no race in CATCH_OTHER if io_exchange throws an error
                    rx = io_exchange(CHANNEL_APDU | flags, rx);
                    flags = 0;

                    // No APDU received; trigger a reset.
                    if (rx == 0)
                    {
                        THROW(EXCEPTION_IO_RESET);
                    }
                    // Malformed APDU.
                    if (G_io_apdu_buffer[OFFSET_CLA] != CLA)
                    {
                        THROW(0x6E00);
                    }
                    // Lookup and call the requested command handler.
                    handler_fn_t* handlerFn = lookupHandler(G_io_apdu_buffer[OFFSET_INS]);
                    if (!handlerFn)
                    {
                        THROW(0x6D00);
                    }
                    handlerFn(G_io_apdu_buffer[OFFSET_P1], G_io_apdu_buffer[OFFSET_P2],
                              G_io_apdu_buffer + OFFSET_CDATA, G_io_apdu_buffer[OFFSET_LC], &flags, &tx);
                }
                CATCH(EXCEPTION_IO_RESET)
                {
                    THROW(EXCEPTION_IO_RESET);
                }
                CATCH_OTHER(e)
                {
                    // Convert the exception to a response code. All error codes
                    // start with 6, except for 0x9000, which is a special
                    // "success" code. Every APDU payload should end with such a
                    // code, even if no other data is sent. For example, when
                    // calcTxnHash is processing packets of txn data, it replies
                    // with just 0x9000 to indicate that it is ready to receive
                    // more data.
                    //
                    // If the first byte is not a 6, mask it with 0x6800 to
                    // convert it to a proper error code. I'm not totally sure why
                    // this is done; perhaps to handle single-byte exception
                    // codes?
                    switch (e & 0xF000)
                    {
                    case 0x6000:
                    case 0x9000:
                        sw = e;
                        break;
                    default:
                        sw = 0x6800 | (e & 0x7FF);
                        break;
                    }
                    G_io_apdu_buffer[tx++] = sw >> 8;
                    G_io_apdu_buffer[tx++] = sw & 0xFF;
                }
                FINALLY
                {
                }
            }
        END_TRY;
        }
    }

// DO NOT EDIT CODE BELOW. IT'S MAGIC
void io_seproxyhal_display(const bagl_element_t* element)
    {
    io_seproxyhal_display_default((bagl_element_t*)element);
    }

unsigned char G_io_seproxyhal_spi_buffer[IO_SEPROXYHAL_BUFFER_SIZE_B];

unsigned char io_event(unsigned char channel)
    {
    // can't have more than one tag in the reply, not supported yet.
    switch (G_io_seproxyhal_spi_buffer[0])
        {
        case SEPROXYHAL_TAG_FINGER_EVENT:
            UX_FINGER_EVENT(G_io_seproxyhal_spi_buffer);
            break;

        case SEPROXYHAL_TAG_BUTTON_PUSH_EVENT:
            UX_BUTTON_PUSH_EVENT(G_io_seproxyhal_spi_buffer);
            break;

        case SEPROXYHAL_TAG_STATUS_EVENT:
            if (G_io_apdu_media == IO_APDU_MEDIA_USB_HID &&
                !(U4BE(G_io_seproxyhal_spi_buffer, 3) &
                    SEPROXYHAL_TAG_STATUS_EVENT_FLAG_USB_POWERED))
                {
                THROW(EXCEPTION_IO_RESET);
                }
            UX_DEFAULT_EVENT();
            break;

        case SEPROXYHAL_TAG_DISPLAY_PROCESSED_EVENT:
            UX_DISPLAYED_EVENT({});
            break;

        case SEPROXYHAL_TAG_TICKER_EVENT:
            UX_TICKER_EVENT(G_io_seproxyhal_spi_buffer, {});
            break;

        default:
            UX_DEFAULT_EVENT();
            break;
        }

    // close the event if not done previously (by a display or whatever)
    if (!io_seproxyhal_spi_is_status_sent())
        {
        io_seproxyhal_general_status();
        }

    // command has been processed, DO NOT reset the current APDU transport
    return 1;
    }

unsigned short io_exchange_al(unsigned char channel, unsigned short tx_len)
    {
    switch (channel & ~(IO_FLAGS))
        {
        case CHANNEL_KEYBOARD:
            break;
            // multiplexed io exchange over a SPI channel and TLV encapsulated protocol
        case CHANNEL_SPI:
            if (tx_len)
                {
                io_seproxyhal_spi_send(G_io_apdu_buffer, tx_len);
                if (channel & IO_RESET_AFTER_REPLIED)
                    {
                    reset();
                    }
                return 0; // nothing received from the master so far (it's a tx transaction)
                }
            else
                {
                return io_seproxyhal_spi_recv(G_io_apdu_buffer, sizeof(G_io_apdu_buffer), 0);
                }
        default:
            THROW(INVALID_PARAMETER);
        }
    return 0;
    }

static void app_exit(void)
    {
    BEGIN_TRY_L(exit)
        {
        TRY_L(exit)
            {
            os_sched_exit(-1);
            }
        FINALLY_L(exit)
            {
            }
        }
    END_TRY_L(exit);
    }

__attribute__((section(".boot"))) int main(void)
    {
    // exit critical section
    __asm volatile("cpsie i");

    for (;;)
        {
        UX_INIT();
        os_boot();
        BEGIN_TRY
            {
                TRY
                {
                    io_seproxyhal_init();
                    USB_power(0);
                    USB_power(1);
                    ui_idle();
                    incognito_main();
                }
                CATCH(EXCEPTION_IO_RESET)
                {
                    // reset IO and UX before continuing
                    continue;
                }
                CATCH_ALL
                {
                    break;
                }
                FINALLY
                {
                }
            }
        END_TRY;
        }
    app_exit();
    return 0;
    }
